const palette = {
  primary: "#2F5242",
  secondary: "#CFA760",
  background: "#FAF9F6",
  card: "#FFFFFF",
  foreground: "#1F2421",
  headerForeground: "#4B4B4B",
  mutedForeground: "#7A756F",
  border: "#E6E4DD",
  destructive: "#B9382D",
  destructiveTransparent: "rgba(185, 56, 45, 0.1)",
  success: "#2E7D32",
  warning: "#D97706",
  warningTransparent: "rgba(217, 119, 6, 0.1)",
  white: "#FFFFFF",
  black: "#000000",
  transparent: "transparent",
  mutedBackground: "#F0EFEC",
};

export const theme = {
  colors: {
    primary: palette.primary,
    secondary: palette.secondary,
    black: palette.black,
    white: palette.white,
    transparent: palette.transparent,
    mainBackground: palette.background,
    mainForeground: palette.foreground,
    headerForeground: palette.headerForeground,
    primaryBackground: palette.primary,
    primaryForeground: palette.white,
    secondaryBackground: palette.secondary,
    secondaryForeground: palette.white,
    cardBackground: palette.card,
    cardForeground: palette.foreground,
    mutedBackground: palette.mutedBackground,
    mutedForeground: palette.mutedForeground,
    inputBackground: palette.white,
    inputForeground: palette.foreground,
    inputBorder: palette.border,
    destructiveBackground: palette.destructive,
    destructiveForeground: palette.white,
    destructiveTransparentBackground: palette.destructiveTransparent,
    success: palette.success,
    warning: palette.warning,
    warningTransparentBackground: palette.warningTransparent,
    buttonPrimaryBackground: palette.primary,
    buttonPrimaryForeground: palette.white,
    buttonSecondaryBackground: palette.transparent,
    buttonSecondaryForeground: palette.primary,
    buttonSecondaryBorder: palette.primary,
    buttonDisabledBackground: palette.border,
    buttonDisabledForeground: palette.mutedForeground,
    border: palette.border,
    shadowColor: palette.black,
  },
  spacing: {
    none: 0,
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
  },
  borderRadii: {
    none: 0,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    round: 999,
  },
  textVariants: {
    defaults: {
      fontFamily: "Inter_400Regular",
      fontSize: 16,
      color: "mainForeground",
      lineHeight: 24,
    },
    header: {
      fontFamily: "Inter_700Bold",
      fontSize: 32,
      color: "headerForeground",
      lineHeight: 40,
      letterSpacing: -0.5,
    },
    subHeader: {
      fontFamily: "Inter_700Bold",
      fontSize: 22,
      color: "primaryBackground",
      lineHeight: 30,
      letterSpacing: -0.25,
    },
    body: {
      fontFamily: "Inter_400Regular",
      fontSize: 16,
      color: "mainForeground",
      lineHeight: 26,
    },
    bodyMedium: {
      fontFamily: "Inter_500Medium",
      fontSize: 16,
      color: "mainForeground",
      lineHeight: 26,
    },
    caption: {
      fontFamily: "Inter_500Medium",
      fontSize: 13,
      color: "mutedForeground",
      lineHeight: 18,
      letterSpacing: 0.2,
    },
    buttonLabel: {
      fontFamily: "Inter_700Bold",
      fontSize: 16,
      color: "buttonPrimaryForeground",
      textAlign: "center",
      letterSpacing: 0.5,
    },
    error: {
      fontFamily: "Inter_500Medium",
      fontSize: 14,
      color: "destructiveBackground",
    },
    sectionHeader: {
      fontFamily: "Inter_700Bold",
      fontSize: 13,
      color: "mutedForeground",
      letterSpacing: 1.5,
      textTransform: "uppercase",
    },
  },
  cardVariants: {
    elevated: {
      backgroundColor: "cardBackground",
      borderRadius: "l",
      padding: "l",
      shadowColor: "shadowColor",
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 12,
      elevation: 4,
    },
  },
  breakpoints: {
    phone: 0,
    tablet: 768,
  },
};
