const palette = {
  primary: "#2F5242",
  secondary: "#CFA760",
  background: "#FAF9F6",
  card: "#FFFFFF",
  foreground: "#1F2421",
  headerForeground: "#4B4B4B",
  mutedForeground: "#7A756F",
  border: "#E6E4DD",
  destructive: "#B9382D",
  destructiveTransparent: "rgba(185, 56, 45, 0.1)",
  success: "#2E7D32",
  warning: "#D97706",
  warningTransparent: "rgba(217, 119, 6, 0.1)",
  white: "#FFFFFF",
  black: "#000000",
  transparent: "transparent",
  mutedBackground: "#F0EFEC",
};

export const theme = {
  colors: {
    primary: palette.primary,
    secondary: palette.secondary,
    black: palette.black,
    white: palette.white,
    transparent: palette.transparent,
    mainBackground: palette.background,
    mainForeground: palette.foreground,
    headerForeground: palette.headerForeground,
    primaryBackground: palette.primary,
    primaryForeground: palette.white,
    secondaryBackground: palette.secondary,
    secondaryForeground: palette.white,
    cardBackground: palette.card,
    cardForeground: palette.foreground,
    mutedBackground: palette.mutedBackground,
    mutedForeground: palette.mutedForeground,
    inputBackground: palette.white,
    inputForeground: palette.foreground,
    inputBorder: palette.border,
    destructiveBackground: palette.destructive,
    destructiveForeground: palette.white,
    destructiveTransparentBackground: palette.destructiveTransparent,
    success: palette.success,
    warning: palette.warning,
    warningTransparentBackground: palette.warningTransparent,
    buttonPrimaryBackground: palette.primary,
    buttonPrimaryForeground: palette.white,
    buttonSecondaryBackground: palette.transparent,
    buttonSecondaryForeground: palette.primary,
    buttonSecondaryBorder: palette.primary,
    buttonDisabledBackground: palette.border,
    buttonDisabledForeground: palette.mutedForeground,
    border: palette.border,
    shadowColor: palette.black,
  },
  spacing: {
    none: 0,
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
  },
  borderRadii: {
    none: 0,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    round: 999,
  },
  textVariants: {
    defaults: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 400,
      fontSize: 16,
      lineHeight: 1.5,
    },
    header: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontSize: 32,
      lineHeight: 1.25,
      letterSpacing: "-0.5px",
    },
    subHeader: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontSize: 22,
      lineHeight: 1.36,
      letterSpacing: "-0.25px",
    },
    body: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 400,
      fontSize: 16,
      lineHeight: 1.625,
    },
    bodyMedium: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 500,
      fontSize: 16,
      lineHeight: 1.625,
    },
    caption: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 500,
      fontSize: 13,
      lineHeight: 1.38,
      letterSpacing: "0.2px",
    },
    buttonLabel: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontSize: 16,
      letterSpacing: "0.5px",
    },
    error: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 500,
      fontSize: 14,
    },
    sectionHeader: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontSize: 13,
      letterSpacing: "1.5px",
      textTransform: "uppercase",
    },
  },
  breakpoints: {
    phone: "0px",
    tablet: "768px",
  },
};

export type Theme = typeof theme;
