const palette = {
  primary: "#2F5242",
  secondary: "#CFA760",
  background: "#FAF9F6",
  card: "#FFFFFF",
  foreground: "#1F2421",
  headerForeground: "#4B4B4B",
  mutedForeground: "#7A756F",
  border: "#E6E4DD",
  destructive: "#B9382D",
  destructiveTransparent: "rgba(185, 56, 45, 0.1)",
  success: "#2E7D32",
  warning: "#D97706",
  warningTransparent: "rgba(217, 119, 6, 0.1)",
  white: "#FFFFFF",
  black: "#000000",
  transparent: "transparent",
  mutedBackground: "#F0EFEC",
};

const spacing = {
  none: 0,
  xs: 4,
  s: 8,
  sm: 12,
  m: 16,
  l: 24,
  xl: 32,
  xxl: 40,
  xxxl: 48,
};

const radii = {
  none: 0,
  s: 8,
  m: 16,
  l: 24,
  xl: 32,
  round: 999,
};

const themeConfig = {
  colors: {
    primary: palette.primary,
    secondary: palette.secondary,
    black: palette.black,
    white: palette.white,
    transparent: palette.transparent,
    mainBackground: palette.background,
    mainForeground: palette.foreground,
    headerForeground: palette.headerForeground,
    primaryBackground: palette.primary,
    primaryForeground: palette.white,
    secondaryBackground: palette.secondary,
    secondaryForeground: palette.white,
    cardBackground: palette.card,
    cardForeground: palette.foreground,
    mutedBackground: palette.mutedBackground,
    mutedForeground: palette.mutedForeground,
    inputBackground: palette.white,
    inputForeground: palette.foreground,
    inputBorder: palette.border,
    destructiveBackground: palette.destructive,
    destructiveForeground: palette.white,
    destructiveTransparentBackground: palette.destructiveTransparent,
    success: palette.success,
    warning: palette.warning,
    warningTransparentBackground: palette.warningTransparent,
    buttonPrimaryBackground: palette.primary,
    buttonPrimaryForeground: palette.white,
    buttonSecondaryBackground: palette.transparent,
    buttonSecondaryForeground: palette.primary,
    buttonSecondaryBorder: palette.primary,
    buttonDisabledBackground: palette.border,
    buttonDisabledForeground: palette.mutedForeground,
    border: palette.border,
    shadowColor: palette.black,
  },
  spacing,
  radii,
  textVariants: {
    defaults: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "16px",
      color: "mainForeground",
      lineHeight: "24px",
      fontWeight: 400,
    },
    header: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "32px",
      color: "headerForeground",
      lineHeight: "40px",
      letterSpacing: "-0.5px",
      fontWeight: 700,
    },
    subHeader: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "22px",
      color: "primaryBackground",
      lineHeight: "30px",
      letterSpacing: "-0.25px",
      fontWeight: 700,
    },
    body: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "16px",
      color: "mainForeground",
      lineHeight: "26px",
      fontWeight: 400,
    },
    bodyMedium: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "16px",
      color: "mainForeground",
      lineHeight: "26px",
      fontWeight: 500,
    },
    caption: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "13px",
      color: "mutedForeground",
      lineHeight: "18px",
      letterSpacing: "0.2px",
      fontWeight: 500,
    },
    buttonLabel: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "16px",
      color: "buttonPrimaryForeground",
      textAlign: "center",
      letterSpacing: "0.5px",
      fontWeight: 700,
    },
    error: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "14px",
      color: "destructiveBackground",
      fontWeight: 500,
    },
    sectionHeader: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "13px",
      color: "mutedForeground",
      letterSpacing: "1.5px",
      textTransform: "uppercase",
      fontWeight: 700,
    },
  },
  cardVariants: {
    elevated: {
      backgroundColor: palette.card,
      borderRadius: `${radii.l}px`,
      padding: `${spacing.l}px`,
      boxShadow: `0 4px 12px rgba(0, 0, 0, 0.08)`,
    },
  },
  breakpoints: {
    phone: "0px",
    tablet: "768px",
  },
};

export const theme = themeConfig;
export type Theme = typeof theme;
